### userApp requests

### registration
POST http://localhost:4000/user-api/register
Content-Type: application/json

{
  "userType":"user",
  "username":"kalpana",
  "password":"password",
  "mail":"kalpana@hotmail.com"
}

### login
POST http://localhost:4000/user-api/login
Content-Type: application/json

{
  "userType":"user",
  "username":"kalpana",
  "password":"password"
}

### get articles of all users
GET http://localhost:4000/user-api/articles

### comments
POST http://localhost:4000/user-api/comment
Content-Type: application/json

{
  "articleId":"1709675320",
  "userName":"nik",
  "comment":"reliable engine"
}