### userApp requests

### registration
POST http://localhost:4000/user-api/registration
Content-Type: application/json

{
  "userType":"user",
  "username":"kalpana",
  "password":"password",
  "mail":"kalpana@hotmail.com"
}

### login
POST http://localhost:4000/user-api/login
Content-Type: application/json

{
  "userType":"user",
  "username":"kalpana",
  "password":"password"
}

### get articles of all users
GET http://localhost:4000/user-api/articles






### authorApp requests

### registration
POST http://localhost:4000/author-api/registration
Content-Type: application/json

{
  "userType":"user",
  "username":"kalpana",
  "password":"password",
  "mail":"kalpana@hotmail.com"
}

### login
POST http://localhost:4000/author-api/login
Content-Type: application/json

{
  "userType":"user",
  "username":"kalpana",
  "password":"password"
}

### get articles of all author
GET http://localhost:4000/author-api/articles














###
GET http://localhost:4000/admin-api/test-admin

###
GET http://localhost:4000/user-api/registration/test-common